title: Ethan E. Berman
description: [A short description of your site purpose]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: [Your Google Analytics tracking ID]
