title: Ethan E. Berman
logo: /assets/bio.png
description: Project Portfolio
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#google_analytics: [Your Google Analytics tracking ID]
